spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Volunteer
    username: root
    password:
    hikari:
      idleTimeout: 500
      connectionTimeout: 15000
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
      temp:
        use_jdbc_metadata_defaults: false
    show-sql: true
  application:
    name: Volunteer

server:
  port: 8080